### ISSUE TITLE
Sigmoid missing

### ISSUE THREAD

**Issue by alwynmathew** [jhornauer/GrUMoDepth#1]
Why does depth estimation layer doesn't have a sigmoid?

https://github.com/jhornauer/GrUMoDepth/blob/01f95fe6a454591ac1c6da41640d49b86549f41b/monodepth2/networks/depth_decoder.py#L139

Do you have sigmoid after `uncertconv` layer?

https://github.com/jhornauer/GrUMoDepth/blob/01f95fe6a454591ac1c6da41640d49b86549f41b/monodepth2/networks/depth_decoder.py#L141

**Comment by jhornauer** [comment]
We use a modified depth decoder for the supervised training on the NYU dataset. In this case, we train the model in a supervised manner with the ground truth depth and do not use a sigmoid activation function in the depth layer since we predict the depth directly. Also, we do not use a sigmoid after the 'uncertconv' layer.
